baseURL = "https://espoir-tramelan.ch/"
description = "L'Espoir Tramelan est un mouvement bénévole qui organise des camps. Le but est de permettre à des enfants et adolescent·e·s de vivre une semaine trépidante avec d'autres jeunes de leur âge. L'accent est mis sur le vécu. Que cela soit par le sport, l'expression, le bricolage, les partages, nous cherchons à communiquer une vie saine aux participant·e·s."
languageCode = "fr-ch"
theme = "espoir"
title = "l'Espoir Tramelan - mouvement bénévole qui organise des camps pour les jeunes (enfants et adolescent·e·s) en Suisse-Romande"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
identifier = "camps"
name = "Les camps"
url = "/camps/"
weight = 2
[[menu.main]]
identifier = "contact"
name = "Nous contacter"
url = "/contact/"
weight = 4
[[menu.main]]
identifier = "faq"
name = "Vos questions"
url = "/faq/"
weight = 3
[[menu.main]]
identifier = "l-espoir-tramelan"
name = "l'Espoir Tramelan"
url = "/l-espoir-tramelan/"
weight = 1
